#include <cuda_runtime.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
 #include <time.h>
#include "taco.h"
extern taco_tensor_t* init_taco_tensor(int32_t order, int32_t csize, int32_t* dimensions);
extern taco_tensor_t* init_taco_tensor_gpu(taco_tensor_t* ht);
extern void fill_array(float* arr, int len);
extern double calc_spent_time(struct timespec end, struct timespec start);
extern double average(double* values, int len);
extern void gpuAssert(cudaError_t code, const char *file, int line, bool abort=true);
#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }

#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;         // 
  int32_t*     dimensions;    // 
  int32_t      csize;         // 
  int32_t*     mode_ordering; // 
  taco_mode_t* mode_types;    // 
  uint8_t***   indices;       // 
  float* vals          // 
  uint8_t*     fill_value;    // 
  int32_t      vals_size;     // 
} taco_tensor_t;
#endif

// Generated by the Tensor Algebra Compiler (tensor-compiler.org)

__global__
void computeDeviceKernel0(taco_tensor_t * __restrict__ a, float &b_val, taco_tensor_t * __restrict__ c, taco_tensor_t * __restrict__ d){
  float* __restrict__ a_vals = (float*)(a->vals);
  float* __restrict__ c_vals = (float*)(c->vals);
  int d1_dimension = (int)(d->dimensions[0]);
  float* __restrict__ d_vals = (float*)(d->vals);

  int32_t i59 = blockIdx.x;
  int32_t i60 = (threadIdx.x % (256));
  if (threadIdx.x >= 256) {
    return;
  }

  int32_t i = i59 * 256 + i60;
  if (i >= d1_dimension)
    return;

  a_vals[i] = b_val * c_vals[i] + d_vals[i];
}

int compute(taco_tensor_t *a, taco_tensor_t *b, taco_tensor_t *c, taco_tensor_t *d) {
  float* __restrict__ b_vals = (float*)(b->vals);
  int d1_dimension = (int)(d->dimensions[0]);

  float* b_val_ptr;
  gpuErrchk(cudaMallocManaged((void**)&b_val_ptr, sizeof(float)));
  float& b_val = *b_val_ptr;
  b_val = b_vals[0];

  computeDeviceKernel0<<<((d1_dimension + 255) / 256), 256>>>(a, b_val, c, d);
  cudaDeviceSynchronize();
  return 0;
}

int main(int argc, char* argv[]){
  int n_runs = atoi(argv[1]);
  if(argc < 2){
    printf("Please specify number of executions!\n");
    exit(1);
  }
  srand(time(0));
  struct timespec start, end_orig, end_taco;
  double* orig_run_times = (double*)malloc(n_runs * sizeof(double));
  double* taco_run_times = (double*)malloc(n_runs * sizeof(double));
  float* a = (float*)malloc(1000000 * sizeof(float));
  float* b = (float*)malloc(1000000 * sizeof(float));
  float m = 1 + ((float)rand()) / RAND_MAX;
  float* c = (float*)malloc(1000000 * sizeof(float));
  int n = 1000000;

  int a_dims[1] = {1000000};
  taco_tensor_t* a_tt = init_taco_tensor(1, sizeof(float), a_dims);
  a_tt->vals = a;
  a_tt = init_taco_tensor_gpu(a_tt);
  int b_dims[1] = {1000000};
  taco_tensor_t* b_tt = init_taco_tensor(1, sizeof(float), b_dims);
  b_tt->vals = b;
  b_tt = init_taco_tensor_gpu(b_tt);
  int m_dims[1] = {1};
  taco_tensor_t* m_tt = init_taco_tensor(1, sizeof(float), m_dims);
  m_tt->vals = &m;
  m_tt = init_taco_tensor_gpu(m_tt);
  int c_dims[1] = {1000000};
  taco_tensor_t* c_tt = init_taco_tensor(1, sizeof(float), c_dims);
  c_tt->vals = c;
  c_tt = init_taco_tensor_gpu(c_tt);

  for(int i = 0; i < n_runs; i++){
    fill_array(a, 1000000);
    fill_array(b, 1000000);
    fill_array(c, 1000000);

    clock_gettime(CLOCK_MONOTONIC, &start);
    // w_vec(a, b, m, c, n);
    clock_gettime(CLOCK_MONOTONIC, &end_orig);

    compute(a_tt, m_tt, b_tt, c_tt);
    clock_gettime(CLOCK_MONOTONIC, &end_taco);

    orig_run_times[i] = calc_spent_time(end_orig, start);
    taco_run_times[i] = calc_spent_time(end_taco, end_orig);
  }

  double orig_time = average(orig_run_times, n_runs);
  double taco_time = average(taco_run_times, n_runs);
  printf("%.5lf %.5lf", orig_time, taco_time);
  return 0;
}
