
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
 #include <time.h>
#include "taco.h"
extern taco_tensor_t* init_taco_tensor(int32_t order, int32_t csize, int32_t* dimensions);

extern void fill_array(float* arr, int len);
extern double calc_spent_time(struct timespec end, struct timespec start);
extern double average(double* values, int len);



#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;          
  int32_t*     dimensions;     
  int32_t      csize;          
  int32_t*     mode_ordering;  
  taco_mode_t* mode_types;     
  uint8_t***   indices;        
  uint8_t*     vals;           
  uint8_t*     fill_value;     
  int32_t      vals_size;      
} taco_tensor_t;
#endif

// Generated by the Tensor Algebra Compiler (tensor-compiler.org)

int compute(taco_tensor_t *a, taco_tensor_t *b, taco_tensor_t *c) {
  float* restrict a_vals = (float*)(a->vals);
  int b1_dimension = (int)(b->dimensions[0]);
  float* restrict b_vals = (float*)(b->vals);
  int c1_dimension = (int)(c->dimensions[0]);
  float* restrict c_vals = (float*)(c->vals);

  float a_val = 0.0;

  for (int32_t i = 0; i < c1_dimension; i++) {
    a_val += b_vals[i] * c_vals[i];
  }

  a_vals[0] = a_val;
  return 0;
}

int main(int argc, char* argv[]){
  int n_runs = atoi(argv[1]);
  if(argc < 2){
    printf("Please specify number of executions!\n");
    exit(1);
  }
  srand(time(0));
  struct timespec start, end_orig, end_taco;
  double* orig_run_times = (double*)malloc(n_runs * sizeof(double));
  double* taco_run_times = (double*)malloc(n_runs * sizeof(double));
  float returnv;
  int NTAPS = 1000000;
  float* input = (float*)malloc(1000000 * sizeof(float));
  float* coefficient = (float*)malloc(1000000 * sizeof(float));

  int returnv_dims[1] = {1};
  taco_tensor_t* returnv_tt = init_taco_tensor(1, sizeof(float), returnv_dims);
  returnv_tt->vals = &returnv;

  int input_dims[1] = {1000000};
  taco_tensor_t* input_tt = init_taco_tensor(1, sizeof(float), input_dims);
  input_tt->vals = input;

  int coefficient_dims[1] = {1000000};
  taco_tensor_t* coefficient_tt = init_taco_tensor(1, sizeof(float), coefficient_dims);
  coefficient_tt->vals = coefficient;


  for(int i = 0; i < n_runs; i++){
    fill_array(input, 1000000);
    fill_array(coefficient, 1000000);

    clock_gettime(CLOCK_MONOTONIC, &start);
     returnv = fir_small(NTAPS, input, coefficient);
    clock_gettime(CLOCK_MONOTONIC, &end_orig);

    compute(returnv_tt, input_tt, coefficient_tt);
    clock_gettime(CLOCK_MONOTONIC, &end_taco);

    orig_run_times[i] = calc_spent_time(end_orig, start);
    taco_run_times[i] = calc_spent_time(end_taco, end_orig);
  }

  double orig_time = average(orig_run_times, n_runs);
  double taco_time = average(taco_run_times, n_runs);
  printf("%.5lf %.5lf", orig_time, taco_time);
  return 0;
}
