
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
 #include <time.h>
#include "taco.h"
extern taco_tensor_t* init_taco_tensor(int32_t order, int32_t csize, int32_t* dimensions);

extern void fill_array(float* arr, int len);
extern double calc_spent_time(struct timespec end, struct timespec start);
extern double average(double* values, int len);



#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;          
  int32_t*     dimensions;     
  int32_t      csize;          
  int32_t*     mode_ordering;  
  taco_mode_t* mode_types;     
  uint8_t***   indices;        
  uint8_t*     vals;           
  uint8_t*     fill_value;     
  int32_t      vals_size;      
} taco_tensor_t;
#endif

// Generated by the Tensor Algebra Compiler (tensor-compiler.org)

int compute(taco_tensor_t *a, taco_tensor_t *b, taco_tensor_t *c, taco_tensor_t *d) {
  int a1_dimension = (int)(a->dimensions[0]);
  float* restrict a_vals = (float*)(a->vals);
  int b1_dimension = (int)(b->dimensions[0]);
  float* restrict b_vals = (float*)(b->vals);
  int c1_dimension = (int)(c->dimensions[0]);
  float* restrict c_vals = (float*)(c->vals);
  int d1_dimension = (int)(d->dimensions[0]);
  float* restrict d_vals = (float*)(d->vals);

  #pragma omp parallel for schedule(runtime)
  for (int32_t i = 0; i < d1_dimension; i++) {
    a_vals[i] = b_vals[i] + c_vals[i] * d_vals[i];
  }
  return 0;
}

int main(int argc, char* argv[]){
  int n_runs = atoi(argv[1]);
  if(argc < 2){
    printf("Please specify number of executions!\n");
    exit(1);
  }
  srand(time(0));
  struct timespec start, end_orig, end_taco;
  double* orig_run_times = (double*)malloc(n_runs * sizeof(double));
  double* taco_run_times = (double*)malloc(n_runs * sizeof(double));
  int N = 1000000;
  float* X = (float*)malloc(1000000 * sizeof(float));
  float* Y = (float*)malloc(1000000 * sizeof(float));
  float* Z = (float*)malloc(1000000 * sizeof(float));

  int X_dims[1] = {1000000};
  taco_tensor_t* X_tt = init_taco_tensor(1, sizeof(float), X_dims);
  X_tt->vals = X;

  int Y_dims[1] = {1000000};
  taco_tensor_t* Y_tt = init_taco_tensor(1, sizeof(float), Y_dims);
  Y_tt->vals = Y;

  int Z_dims[1] = {1000000};
  taco_tensor_t* Z_tt = init_taco_tensor(1, sizeof(float), Z_dims);
  Z_tt->vals = Z;


  for(int i = 0; i < n_runs; i++){
    fill_array(X, 1000000);
    fill_array(Y, 1000000);
    fill_array(Z, 1000000);

    clock_gettime(CLOCK_MONOTONIC, &start);
 mult_add_into_cpu(N, X, Y, Z);
    clock_gettime(CLOCK_MONOTONIC, &end_orig);

    compute(X_tt, Y_tt, Z_tt, Z_tt);
    clock_gettime(CLOCK_MONOTONIC, &end_taco);

    orig_run_times[i] = calc_spent_time(end_orig, start);
    taco_run_times[i] = calc_spent_time(end_taco, end_orig);
  }

  double orig_time = average(orig_run_times, n_runs);
  double taco_time = average(taco_run_times, n_runs);
  printf("%.5lf %.5lf", orig_time, taco_time);
  return 0;
}
